# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  build-publish:
    env:
      workdir: healthmodelpanel
      package_version: ${{github.event.release.tag_name}}
    defaults: 
      run: 
        working-directory: ${{env.workdir}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install

      - run: yarn build
  
      - run: cp package.json dist

      - run: |
          npm version ${{env.package_version}}
          npm publish
        working-directory: ${{env.workdir}}/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
