# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      workdir: healthmodelpanel
      package_version: ${{github.event.release.tag_name}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: yarn install
        working-directory: ${{env.workdir}}

      - run: yarn build
        working-directory: ${{env.workdir}}
  
      - run: cp package.json dist
        working-directory: ${{env.workdir}}

      - run: npm version ${{env.package_version}}
        working-directory: ${{env.workdir}}/dist

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        working-directory: ${{env.workdir}}/dist
        with:
          token: ${{secrets.GITHUB_TOKEN}}